### PR TITLE
feat(rules): add vrsource-tslint-rules/multiline-arrow

### LINKED ISSUE #145: tslint-config-prettier conflicts with rule "multiline-arrow" from "vrsource-tslint-rules"

### PR DESCRIPTION
**Pull request by ikatyang**
Fixes #145

### CODE REVIEW

**Comment by sharikovvladislav** [comment]
LuL. Space speed. I wanted to open the PR, but you are insanely fast :)

**Comment by alexjoverm** [comment]
Thanks a lot @ikatyang!

**Pull request merged**
